/* eslint-disable import/no-anonymous-default-export */
export default {
  lorem: () => (
    <>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ultrices, eros nec dictum dapibus, arcu augue consectetur sem, ut sodales sapien ligula vitae enim. Nunc euismod eros nisi, sit amet finibus dolor sagittis id. Donec eget nunc sapien. Nulla pellentesque quis justo vitae elementum. Duis tincidunt placerat rhoncus. Mauris varius nunc metus, eget suscipit ligula euismod sit amet. Vestibulum mattis dui sit amet risus posuere blandit. Proin consectetur justo quis urna pharetra luctus. Etiam luctus porta vestibulum. Donec facilisis iaculis risus, sit amet hendrerit risus ornare quis. Duis rutrum mollis sapien ac maximus. Aenean non fringilla urna, a pulvinar tortor.</p>
      <p>Morbi vitae nunc vel neque condimentum lacinia et eget urna. Nam vitae magna elit. Nulla lacinia ex justo, eu aliquam purus efficitur a. Vestibulum nec laoreet felis. Cras volutpat est in pretium bibendum. Morbi lacinia venenatis lacus, quis pretium augue condimentum ac. In dictum elit porta, tristique lectus quis, elementum felis.</p>
      <p>Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Pellentesque et quam a urna lacinia rutrum. Aenean ultricies scelerisque lacus sit amet tincidunt. Nunc accumsan in mi vitae porttitor. Maecenas nec nisl ut ante placerat ultrices at vitae elit. Donec et quam risus. Integer lectus neque, tincidunt a auctor vitae, aliquet ut sapien. Vestibulum id libero quis purus egestas aliquet. Nunc eu nulla ullamcorper, volutpat turpis eu, convallis nunc. Vivamus ac finibus justo, eget accumsan metus.</p>
      <p>Nulla viverra lectus ac euismod consequat. Proin congue, nisi at pellentesque condimentum, quam dolor scelerisque justo, et hendrerit mauris eros facilisis massa. Donec accumsan mauris tellus. Aenean eget dolor ac urna ullamcorper tempus. Aliquam malesuada risus vel fringilla tempor. Fusce ultrices eros non elementum sodales. Quisque id commodo tellus. Morbi convallis risus ut accumsan bibendum. Ut tincidunt, nulla hendrerit commodo aliquam, enim elit tristique eros, et accumsan eros ligula at nibh. Ut lorem augue, venenatis quis imperdiet eget, semper nec arcu. Phasellus vitae ex est. Duis gravida, massa nec pulvinar fringilla, dolor enim tristique eros, eget pulvinar risus magna eu neque. Phasellus nec sem tellus. Curabitur non ligula nec quam efficitur eleifend interdum sed arcu. Vivamus luctus pellentesque lorem ut tincidunt.</p>
      <p>Ut euismod consectetur nisl eu fermentum. Aenean quis enim facilisis, varius tellus molestie, pharetra mi. In hac habitasse platea dictumst. Sed tincidunt ex nec pharetra aliquet. Aenean tincidunt, ligula eget lobortis iaculis, dui leo volutpat elit, vel laoreet urna leo id ante. Praesent sit amet vulputate diam. Phasellus sit amet mi non nunc volutpat pretium. In tincidunt laoreet elementum. Suspendisse tristique neque sit amet nisi efficitur, ultrices lacinia dui elementum. Proin mattis lorem et magna vestibulum lacinia. Vivamus pharetra laoreet tempor. Aliquam ac mollis eros, in mattis risus. Proin iaculis tortor ac nibh molestie, vitae dictum ipsum ornare. Integer rutrum sapien neque, in ornare arcu imperdiet non.</p>
    </>
  )
};
